server:
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8080
#    uri-encoding: utf-8
#security:
#  basic:
#    enabled: false
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
logging:
  level:
    root: info
    com.bootdo: debug
  config: classpath:logback-dev.xml